language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
jobs:
  include:
    - stage: deploy
      rust: stable
deploy:
  provider: cargo
  token:
    secure: xSdD9k4TcYs6Xjmx50b15kR2b+qJEPWIfqSsw1J9iA7Aj5LqnXHONxZqxPxFdiEzAS5taRRSf0tTfikkyP3GKp5eM5yM0SnytJ9cAFO0LxbUDitOJjxRVk0FfDnCRSQmyyIHZkzIBh4coK72B4ntPDT68xyVxArLV3ngsfx03hd/v19SMUGAr4qb9HPdXrD+Y2K+wV55ILyQ/9xNQcKIa5FMdIAp37XgEmbOko1CbaSugMUrNqGZanMKPph4ft4cLT7LQFG1Z/zQXUfns8Vx7xtuvxH400ixa1bbmbwRTI7wn4qs3mNPJyQEqBEOZeYzjfZkv2gXLgYXEs7vwHmaJzGBSOyB2sYP2mXLREmcS8PSojFKlmy9HYAMLMEwuYm1CCODhV1H5xZDaLoyJCVxXACynp1B/iWMlsU5inZLrtSOkVTTRBffhHTYK7PKrfem0crs+NJZo4z9GV+dnNRAj3itoo1zrctakRDoMFG0WNj6ZzA8avLWmLK9v5vokfT5WM2APsgr4Uu3g49Vi1oG6RPolUoF1BuPZR3As5qxSfTSr1tKET+p/hpnlrcHorBJBFgNkeQNoC2j6BEUsCF14J3A8C5XJ2qgOCKsa+as01xlMCoAMNoI6grrNWbgQYA6ffwtn3OzUq0ZeW1TrCmBDZF7qiZQujf6c1dMu4zcOeI=
  on:
    tags: true
cache: cargo
