language: rust
rust:
- stable
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
deploy:
  provider: cargo
  token:
    secure: CAt8QNlzjmvEOxNoPAYQQibdWKrEDy+VKk8dR7Ch78DQQTqS2iy/9UMBfpiL8XnSlf12TKYvyYRwd7b9hM2mqgwJMI6vK1x54EsN9BYBMUFfiyjhQuA7xbnjge09mrVFoRB+PugjXMQNqNosuP9CtK7YNn4ATXQPqMC2mt9EBZlrEraAg0wuh6ivXehq2z2ap56Se3lEWExI0DovMbwI63jxP3Q+robfaoeCCV0avP/u5kSbJUgoYkb/l7NH3Nf/Yh0WHF73fLAUMFwnCntqrF+dc2zKuC8dMgwqDqTl0TkZpQ+U7HMO3TYayDHhS0lL3gkfE21YInFJydYbbB15RRDsS/W8cRd68Dlwlvk2fKnyFmrafFi2eGYgGf8oekE8RuRp2eNeIxxnTdFO4xmNH+5vZg11zJemoUOV1FASzjGalKGik6giY3VGldK405++s5n62Qg30KqxfIkCY1XZyMfboJp4KihTJyfKkHqrOiNFsWCmWHIB0EzsdQjlH87O5qivmW2/h/mYwpCgq/WSRh9BuDb3LUloJLaU4FPbBy8ProtkXxzSJHYjCq82I8DmfydylBhPdr4Q9P/UK1O17JxgKSe+6dQiyuAzRDHm/Fle+v61yNNnlP+P5qzke48DuhvXuOF7BTrDNFksThJkC2WCX3FnwfYJhVlDYKDRYfw=
  on:
    tags: true
cache: cargo
